[package]
name = "wasmedge_longjump"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.141"
scoped-tls = "1.0.1"
setjmp = "0.1"
wasmedge-sdk = "0.7.1"
wasmedge-types = "0.3.1"
